import '../models/receita.dart';

// sementes usadas para popular o banco no primeiro uso
final List<Receita> receitasSeed = [
  Receita(
    id: 1,
    nome: 'Macarrão ao Alho e Óleo',
    descricao: 'Rápido, fácil e delicioso para o dia a dia.',
    imagemUrl: 'assets/images/macarrao-alho-e-oleo.jpg',
    tempoMinutos: 15,
    porcoes: 2,
    dificuldade: 'Fácil',
    categoria: 'Jantar',
    destaque: true,
    ingredientes: const [
      Ingrediente(nome: 'Macarrão', quantidade: '200g'),
      Ingrediente(nome: 'Alho', quantidade: '4 dentes'),
      Ingrediente(nome: 'Azeite', quantidade: '4 colheres'),
      Ingrediente(nome: 'Salsinha', quantidade: 'a gosto'),
      Ingrediente(nome: 'Sal e pimenta', quantidade: 'a gosto'),
    ],
    modoPreparo: const [
      'Cozinhe o macarrão conforme as instruções da embalagem.',
      'Em uma frigideira, aqueça o azeite e doure o alho fatiado.',
      'Adicione o macarrão escorrido e misture bem.',
      'Finalize com salsinha, sal e pimenta a gosto.',
    ],
  ),
  Receita(
    id: 2,
    nome: 'Omelete de Queijo',
    descricao: 'Café da manhã proteico em menos de 10 minutos.',
    imagemUrl: 'assets/images/omelete-de-queijo.jpg',
    tempoMinutos: 10,
    porcoes: 1,
    dificuldade: 'Fácil',
    categoria: 'Café da Manhã',
    destaque: true,
    ingredientes: const [
      Ingrediente(nome: 'Ovos', quantidade: '3 unidades'),
      Ingrediente(nome: 'Queijo mussarela', quantidade: '50g'),
      Ingrediente(nome: 'Sal', quantidade: 'a gosto'),
      Ingrediente(nome: 'Manteiga', quantidade: '1 colher'),
    ],
    modoPreparo: const [
      'Bata os ovos com sal em uma tigela.',
      'Derreta a manteiga em frigideira antiaderente.',
      'Despeje os ovos e cozinhe em fogo médio.',
      'Adicione o queijo antes de dobrar a omelete.',
      'Dobre ao meio e sirva quente.',
    ],
  ),
  Receita(
    id: 3,
    nome: 'Frango Grelhado com Limão',
    descricao: 'Proteína magra temperada com ervas e limão.',
    imagemUrl: 'assets/images/frango-grelhado-com-limao.jpg',
    tempoMinutos: 20,
    porcoes: 2,
    dificuldade: 'Médio',
    categoria: 'Almoço',
    destaque: true,
    ingredientes: const [
      Ingrediente(nome: 'Filé de frango', quantidade: '2 unidades'),
      Ingrediente(nome: 'Limão', quantidade: '1 unidade'),
      Ingrediente(nome: 'Alho', quantidade: '2 dentes'),
      Ingrediente(nome: 'Azeite', quantidade: '2 colheres'),
      Ingrediente(nome: 'Sal e pimenta', quantidade: 'a gosto'),
      Ingrediente(nome: 'Orégano', quantidade: 'a gosto'),
    ],
    modoPreparo: const [
      'Tempere o frango com limão, alho, sal, pimenta e orégano.',
      'Deixe marinar por 10 minutos.',
      'Aqueça uma grelha com azeite em fogo alto.',
      'Grelhe o frango por 5-7 minutos de cada lado.',
    ],
  ),
  Receita(
    id: 4,
    nome: 'Salada Caesar',
    descricao: 'Clássico da culinária americana, fresco e saboroso.',
    imagemUrl: 'assets/images/salada-caesar.jpg',
    tempoMinutos: 10,
    porcoes: 2,
    dificuldade: 'Fácil',
    categoria: 'Almoço',
    destaque: false,
    ingredientes: const [
      Ingrediente(nome: 'Alface romana', quantidade: '1 pé'),
      Ingrediente(nome: 'Croutons', quantidade: '1 xícara'),
      Ingrediente(nome: 'Parmesão ralado', quantidade: '50g'),
      Ingrediente(nome: 'Molho Caesar', quantidade: '4 colheres'),
    ],
    modoPreparo: const [
      'Lave e rasgue a alface em pedaços.',
      'Misture o molho Caesar com a alface.',
      'Adicione os croutons e o parmesão.',
      'Sirva imediatamente.',
    ],
  ),
  Receita(
    id: 5,
    nome: 'Ovos Mexidos',
    descricao: 'Cremoso e rápido, perfeito para o café da manhã.',
    imagemUrl: 'assets/images/ovo-mexido.jpg',
    tempoMinutos: 8,
    porcoes: 1,
    dificuldade: 'Fácil',
    categoria: 'Café da Manhã',
    destaque: false,
    ingredientes: const [
      Ingrediente(nome: 'Ovos', quantidade: '3 unidades'),
      Ingrediente(nome: 'Manteiga', quantidade: '1 colher'),
      Ingrediente(nome: 'Sal e pimenta', quantidade: 'a gosto'),
      Ingrediente(nome: 'Cebolinha', quantidade: 'a gosto'),
    ],
    modoPreparo: const [
      'Bata os ovos com sal e pimenta.',
      'Derreta a manteiga em fogo baixo.',
      'Adicione os ovos e mexa lentamente.',
      'Retire antes de firmar completamente.',
      'Finalize com cebolinha picada.',
    ],
  ),
  Receita(
    id: 6,
    nome: 'Vitamina de Banana',
    descricao: 'Energética e nutritiva, pronta em 5 minutos.',
    imagemUrl: 'assets/images/vitamina-banana.jpg',
    tempoMinutos: 5,
    porcoes: 1,
    dificuldade: 'Fácil',
    categoria: 'Lanches',
    destaque: true,
    ingredientes: const [
      Ingrediente(nome: 'Banana', quantidade: '2 unidades'),
      Ingrediente(nome: 'Leite', quantidade: '200ml'),
      Ingrediente(nome: 'Mel', quantidade: '1 colher'),
      Ingrediente(nome: 'Canela', quantidade: 'a gosto'),
    ],
    modoPreparo: const [
      'Descasque as bananas e corte em pedaços.',
      'Bata no liquidificador com o leite e o mel.',
      'Polvilhe canela por cima.',
      'Sirva gelado.',
    ],
  ),
];
